=== Leyli2020/candy_project/src/main/resources/candy.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="candies">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="candy" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

    <xs:element name="candy">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element ref="energy"/>
                <xs:element ref="type"/>
                <xs:element ref="ingredients"/>
                <xs:element name="date" type="xs:date"/>
                <xs:element ref="value"/>
                <xs:element name="production" type="xs:string"/>
            </xs:sequence>
            <xs:attribute ref="id" use="required" />
        </xs:complexType>
    </xs:element>



    <xs:element name="energy">
        <xs:simpleType>
            <xs:restriction base="xs:nonNegativeInteger">
                <xs:maxInclusive value="1000"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="type">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="caramel"/>
                <xs:enumeration value="chocolate"/>
                <xs:enumeration value="iris"/>
                <xs:enumeration value="with filling"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="ingredients">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ingredient"  maxOccurs="5"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="ingredient">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="quantity" type="xs:positiveInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="value">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="proteins" type="xs:decimal"/>
                <xs:element name="fats" type="xs:decimal"/>
                <xs:element name="carbohydrates" type="xs:decimal"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>



    <xs:attribute name="id" type="xs:positiveInteger"/>
</xs:schema>

=== Leyli2020/candy_project/src/main/resources/candy.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="candy.xsd">
    <candy id="1">
        <name>Konti</name>
        <energy>500</energy>
        <type>caramel</type>
        <ingredients>
            <ingredient>
                <name>water</name>
                <quantity>23</quantity>
            </ingredient>
            <ingredient>
                <name>Sugar</name>
                <quantity>50</quantity>
            </ingredient>
            <ingredient>
                <name>milk chocolate</name>
                <quantity>30</quantity>
            </ingredient>
        </ingredients>
        <date>2022-03-19</date>
        <value>
            <proteins>2.5</proteins>
            <fats>28</fats>
            <carbohydrates>70</carbohydrates>
        </value>
        <production>Conti</production>
    </candy>
    <candy id="2">
        <name>Bubble</name>
        <energy>900</energy>
        <type>chocolate</type>
        <ingredients>
            <ingredient>
                <name>water</name>
                <quantity>67</quantity>
            </ingredient>
            <ingredient>
                <name>Sugar</name>
                <quantity>80</quantity>
            </ingredient>
            <ingredient>
                <name>milk chocolate</name>
                <quantity>30</quantity>
            </ingredient>
        </ingredients>
        <date>2022-03-20</date>
        <value>
            <proteins>3.5</proteins>
            <fats>38</fats>
            <carbohydrates>80</carbohydrates>
        </value>
        <production>Bubble</production>
    </candy>
    <candy id="3">
        <name>Korovka</name>
        <energy>500</energy>
        <type>iris</type>
        <ingredients>
            <ingredient>
                <name>water</name>
                <quantity>67</quantity>
            </ingredient>
            <ingredient>
                <name>Sugar</name>
                <quantity>80</quantity>
            </ingredient>
            <ingredient>
                <name>milk chocolate</name>
                <quantity>30</quantity>
            </ingredient>
        </ingredients>
        <date>2022-03-22</date>
        <value>
            <proteins>3.5</proteins>
            <fats>38</fats>
            <carbohydrates>62</carbohydrates>
        </value>
        <production>Roshen</production>
    </candy>
</candies>
